FROM alpine:3

LABEL author="sandriansyafridev"
LABEL company="com.sandriansyafridev"
LABEL website="https://google.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt" 