FROM alpine:3


#create file name is hello-world.txt
RUN touch hello-world.txt 

#create directory folder name is hello
RUN mkdir hello

#write "Hello World" using echo command
RUN echo "Hello World" > hello-world.txt

#display output in hello-world.txt using cat command
RUN cat hello-world.txt



